apiVersion: v1
kind: Service
metadata:
  name: {{ include "theia.fullname" . }}
  labels:
    {{- include "theia.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.port2 }}
      targetPort: http2
      protocol: TCP
      name: http2
  selector:
    {{- include "theia.selectorLabels" . | nindent 4 }}
